<?php
/**
 * This file is part of the Semaio_CustomSku module.
 *
 * See LICENSE.md bundled with this module for license details.
 *
 * @category  Semaio
 * @package   Semaio_CustomSku
 * @author    semaio GmbH <hello@semaio.com>
 * @copyright 2016 semaio GmbH (http://www.semaio.com)
 */
/**
 * @var $this Semaio_CustomSku_Block_Info
 */
?>
<?php if ($_customSku = $this->getCustomSku()): ?>
    <div class="checkout-custom-sku">
        <span class="label"><?php echo $this->__('Your custom SKU:'); ?></span> <?php echo $this->escapeHtml($_customSku); ?>
    </div>
<?php endif; ?>
